const constants = {
    LOAD_ARTICLES: 'LOAD_ARTICLES',
    LOAD_SYSTEM_DETAILS: 'LOAD_SYSTEM_DETAILS',
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    CLEAR_ARTICLES: 'CLEAR_ARTICLES',
    LOAD_SOURCES: 'LOAD_SOURCES',
    LOAD_COUNTRIES: 'LOAD_COUNTRIES',
    SELECTED_COUNTRY: 'SELECTED_COUNTRY',
    LOADING_FLAG: 'LOADING_FLAG'
};

export default constants;