const constants = {
    LOAD_ARTICLES: 'LOAD_ARTICLES',
    LOAD_SYSTEM_DETAILS: 'LOAD_SYSTEM_DETAILS',
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
    CLEAR_ARTICLES: 'CLEAR_ARTICLES',
    LOAD_SOURCES: 'LOAD_SOURCES'
};

export default constants;